### ISSUE TITLE
Plans for code release

### ISSUE THREAD

**Issue by kis-balazs** [1hao-Liu/SM4Depth#1]
Hi,

very intriguing work, what you did here. We would love to be able to try it out/run it for our use-cases.

Is there any plan to release the code? And if yes, what components/modules are planned?

Thank you!

**Comment by 1hao-Liu** [comment]
@kis-balazs Thank you for your attention!
---

Code and datasets will be released soon.


backbone = Swin Transformer base
decoder = DPT's decoder
and used a PST module (from DANet) between backbone and decoder

**Comment by kis-balazs** [comment]
Could you please define "soon"? :)

**Comment by Snailgoo** [comment]
> ## @kis-balazs Thank you for your attention!
> Code and datasets will be released soon.
> 
> backbone = Swin Transformer base decoder = DPT's decoder and used a PST module (from DANet) between backbone and decoder

half a year has passed ，is the code any progress？

**Comment by kis-balazs** [comment]
Since I asked, we even released a new [evaluation method](https://leisemann.github.io/ca_mmde/); we're already not only interested in the publication for it's advancement, we're ready to objectively measure its performance against other methods :)

**Comment by xuefeng-cvr** [comment]
The code of test has been released.
